version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    container_name: orderservice
    ports:
      - "5001:80"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Database=ordersdb;User Id=postgres;Password=yourpassword;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672

  paymentservice:
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    container_name: paymentservice
    ports:
      - "5002:80"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Database=paymentsdb;User Id=postgres;Password=yourpassword;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672

volumes:
  pgdata:
